Repository hail-is/hail, pull requests merged in 2018-04, with the labels that each got.

#3279 Fix aggregate_entries index issue
  python/hail/tests/test_api.py
  src/main/scala/is/hail/variant/MatrixTable.scala
Labels: tiny PR

#3182 [0.1] Allow empty strings in BGEN reader
  build.gradle
  deployed-spark-versions.txt
  python/hail/docs/_ext/hail_doctest.py
  src/main/scala/is/hail/io/AbstractBinaryReader.scala
Labels: 0.1

#2924 add traverse_fields
  python/hail/expr.py
  python/hail/tests/tests.py
Labels: 0.1

#3263 one fewer scalarDiv in PCRelate
  src/main/scala/is/hail/methods/PCRelate.scala
Labels: tiny PR

#2958 link to devel in navbar [0.1]
  python/hail/docs/_templates/layout.html
  python/hail/docs/_templates/navbar_hail.html
  www/navbar.html
Labels: 0.1

#3196 hopefully fix dylib issue
  src/main/c/lib/darwin/libhail.dylib
Labels: 0.1

#3295 linear_regression ys => y, return scalar annotations when y is not list
  python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
  python/hail/methods/statgen.py
  python/hail/tests/test_methods.py
  src/main/scala/is/hail/methods/LinearRegression.scala
  src/main/scala/is/hail/variant/MatrixTable.scala
Labels: breaking change

#3331 fix missing export
  python/hail/expr/types.py
Labels: prio:high

#3338 fix bad link on homepage
  README.md
Labels: tiny PR

#3351 Check key in python for table join
  python/hail/table.py
Labels: tiny PR

#3437 Fixes #3436
  python/hail/tests/test_expr.py
  src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
Labels: bug

#3456 Fix Bind AST node to wrap in parens
  python/hail/expr/expr_ast.py
  python/hail/tests/test_expr.py
Labels: tiny PR
