Repository hail-is/hail, pull requests merged in 2018-08, with the labels that each got.

#4079 Add files created by test run to .gitignore
  .gitignore
Labels: tiny PR

#4067 Optional intercept in regressions and skat
  python/hail/docs/tutorials/01-genome-wide-association-study.ipynb
  python/hail/docs/tutorials/plotting.ipynb
  python/hail/expr/aggregators/aggregators.py
  python/hail/methods/statgen.py
  python/test/hail/methods/test_statgen.py
  src/main/scala/is/hail/methods/LinearRegression.scala
  src/main/scala/is/hail/methods/LogisticRegression.scala
  src/main/scala/is/hail/methods/Skat.scala
  src/main/scala/is/hail/stats/LogisticRegressionModel.scala
  src/main/scala/is/hail/stats/RegressionUtils.scala
  src/test/scala/is/hail/methods/SkatSuite.scala
  src/test/scala/is/hail/testUtils/RichMatrixTable.scala
Labels: breaking change

#4092 revert getting started link changes
  README.md
  python/hail/docs/getting_started.rst
  python/hail/docs/getting_started_developing.rst
  python/hail/docs/index.rst
Labels: tiny PR

#4076 write SplitMulti in python (take 2)
  python/hail/docs/methods/genetics.rst
  python/hail/docs/methods/index.rst
  python/hail/expr/functions.py
  python/hail/matrixtable.py
  python/hail/methods/__init__.py
  python/hail/methods/misc.py
  python/hail/methods/statgen.py
  python/test/hail/methods/test_statgen.py
  src/main/scala/is/hail/methods/SplitMulti.scala
  src/main/scala/is/hail/rvd/OrderedRVDPartitioner.scala
  src/test/scala/is/hail/TestUtils.scala
Labels: breaking change

#4104 seeded randomness in functions
  python/hail/__init__.py
  python/hail/context.py
  python/hail/docs/api.rst
  python/hail/docs/functions/random.rst
  python/hail/docs/overview.rst
  python/hail/expr/functions.py
  python/hail/ir/ir.py
  python/hail/utils/java.py
  python/test/hail/expr/test_expr.py
  python/test/hail/utils/test_utils.py
  src/main/scala/is/hail/expr/Parser.scala
  src/main/scala/is/hail/expr/ir/Children.scala
  src/main/scala/is/hail/expr/ir/Compile.scala
  src/main/scala/is/hail/expr/ir/Copy.scala
  src/main/scala/is/hail/expr/ir/Emit.scala
  src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
  src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
  src/main/scala/is/hail/expr/ir/FoldConstants.scala
  src/main/scala/is/hail/expr/ir/IR.scala
  src/main/scala/is/hail/expr/ir/Interpret.scala
  src/main/scala/is/hail/expr/ir/MatrixIR.scala
  src/main/scala/is/hail/expr/ir/Pretty.scala
  src/main/scala/is/hail/expr/ir/Simplify.scala
  src/main/scala/is/hail/expr/ir/TableIR.scala
  src/main/scala/is/hail/expr/ir/TableValue.scala
  src/main/scala/is/hail/expr/ir/TypeCheck.scala
  src/main/scala/is/hail/expr/ir/functions/Functions.scala
  src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
  src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala
  src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
  src/main/scala/is/hail/rvd/OrderedRVD.scala
  src/main/scala/is/hail/rvd/RVD.scala
  src/main/scala/is/hail/rvd/UnpartitionedRVD.scala
  src/main/scala/is/hail/sparkextras/ContextRDD.scala
  src/main/scala/is/hail/stats/package.scala
  src/main/scala/is/hail/utils/Graph.scala
  src/test/scala/is/hail/TestUtils.scala
  src/test/scala/is/hail/expr/ir/FunctionSuite.scala
  src/test/scala/is/hail/expr/ir/IRSuite.scala
  src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
  src/test/scala/is/hail/expr/ir/OrderingSuite.scala
  src/test/scala/is/hail/expr/ir/RandomFunctionsSuite.scala
  src/test/scala/is/hail/stats/StatsSuite.scala
  src/test/scala/is/hail/variant/ReferenceGenomeSuite.scala
Labels: breaking change

#3872 VEP properties json
  python/hail/methods/qc.py
  src/main/scala/is/hail/expr/AnnotationImpex.scala
  src/main/scala/is/hail/methods/VEP.scala
Labels: breaking change

#4136 Switching min_rep to return struct with locus and alleles
  python/hail/expr/functions.py
  python/hail/methods/statgen.py
  python/test/hail/expr/test_expr.py
  src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala
Labels: breaking change

#4145 more random functions
  python/hail/docs/functions/index.rst
  python/hail/docs/functions/random.rst
  python/hail/expr/__init__.py
  python/hail/expr/functions.py
  python/test/hail/expr/test_expr.py
  src/main/scala/is/hail/expr/ir/functions/Functions.scala
  src/main/scala/is/hail/expr/ir/functions/RandomSeededFunctions.scala
  src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
Labels: breaking change

#4158 fix link to aggregators module on scan page
  python/hail/docs/scans.rst
Labels: tiny PR

#4161 remove duplicate api link from sidebar
  python/hail/docs/index.rst
Labels: tiny PR

#4168 fix swapped links
  README.md
Labels: tiny PR

#4180 fix LinearMixedModel bug
  python/hail/stats/linear_mixed_model.py
  python/test/hail/stats/test_linear_mixed_model.py
Labels: tiny PR

#4179 fix filter_intervals doc
  python/hail/methods/misc.py
Labels: tiny PR

#4150 add VEP csq header definition to globals when csq=true
  python/hail/methods/qc.py
  src/main/scala/is/hail/methods/VEP.scala
Labels: gnomAD

#4205 Deleted dead match case
  src/main/scala/is/hail/expr/ir/IR.scala
Labels: tiny PR

#4206 Fix typo in CallExpression.is_het_non_ref
  python/hail/expr/expressions/typed_expressions.py
  python/test/hail/expr/test_expr.py
Labels: breaking change

#4151 Elasticsearch v6.3
  build.gradle
Labels: 0.1
