Repository hail-is/hail, pull requests merged in 2018-09, with the labels that each got.

#4336 Fix docs for adding pretty printing in python
  hail/src/main/scala/is/hail/expr/ir/add-ir-checklist.txt
Labels: tiny PR

#4335 Change behavior of _to_table for column and entry fields
  hail/python/hail/expr/expressions/base_expression.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
Labels: breaking change

#4383 Clean up relational slice syntax 1
  hail/python/hail/matrixtable.py
  hail/python/hail/table.py
Labels: breaking change

#4413 Fix SplitMulti docs references
  hail/python/hail/docs/_templates/req_biallelic.rst
  hail/python/hail/methods/statgen.py
Labels: documentation, tiny PR

#4387 Rename Expression.value to Expression.eval()
  hail/python/hail/docs/functions/core.rst
  hail/python/hail/docs/functions/index.rst
  hail/python/hail/docs/functions/random.rst
  hail/python/hail/docs/hailpedia/expressions.rst
  hail/python/hail/docs/tutorials/03-expressions.ipynb
  hail/python/hail/docs/tutorials/07-filter-annotate.ipynb
  hail/python/hail/expr/__init__.py
  hail/python/hail/expr/builders.py
  hail/python/hail/expr/expressions/__init__.py
  hail/python/hail/expr/expressions/base_expression.py
  hail/python/hail/expr/expressions/expression_utils.py
  hail/python/hail/expr/expressions/typed_expressions.py
  hail/python/hail/expr/functions.py
  hail/python/hail/methods/impex.py
  hail/python/hail/methods/misc.py
  hail/python/hail/methods/qc.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/genetics/test_reference_genome.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/methods/test_misc.py
  hail/python/test/hail/methods/test_statgen.py
  hail/python/test/hail/table/test_table.py
  hail/python/test/hail/test_ir.py
Labels: breaking change
