Repository hail-is/hail, pull requests merged in 2018-06, with the labels that each got.

#3703 Test *.rst files
  python/hail/conftest.py
  python/hail/docs/doctest.sh
  python/hail/docs/getting_started.rst
  python/hail/docs/getting_started_developing.rst
  python/hail/docs/overview.rst
Labels: bug

#3724 Fix MatrixAggregateColsByKey and MatrixAggregateRowsByKey
  python/hail/tests/test_api.py
  python/hail/tests/test_expr.py
  src/main/scala/is/hail/expr/Relational.scala
Labels: bug

#3735 fix bug with incorrect key index in LocalLDPrune
  src/main/scala/is/hail/methods/LocalLDPrune.scala
  src/test/scala/is/hail/methods/LocalLDPruneSuite.scala
Labels: bug

#3784 IR for array rpois, isnan, and signum (now sign)
  python/hail/expr/__init__.py
  python/hail/expr/functions.py
  python/hail/tests/test_expr.py
  src/main/scala/is/hail/expr/FunctionRegistry.scala
  src/main/scala/is/hail/expr/ir/functions/MathFunctions.scala
  src/main/scala/is/hail/stats/package.scala
  src/test/scala/is/hail/expr/ir/MathFunctionsSuite.scala
Labels: breaking change

#3796 Fix Aggregable IR FlatMap
  src/main/scala/is/hail/expr/AST.scala
Labels: bug

#3762 make MatrixTable.group_by.aggregate_rows/cols work with implicit joins
  python/hail/matrixtable.py
  python/hail/table.py
  python/hail/tests/test_api.py
Labels: bug

#3820 fix link to locus_from_global_position in docs
  python/hail/expr/expressions/typed_expressions.py
Labels: tiny PR

#3836 fix #3835 ld prune bug when there are duplicate row keys
  python/hail/methods/statgen.py
  python/hail/tests/test_methods.py
  src/main/scala/is/hail/methods/UpperIndexBounds.scala
Labels: bug

#3858 fix liftover functions to handle missing return
  python/hail/tests/test_genetics.py
  src/main/scala/is/hail/expr/ir/functions/ReferenceGenomeFunctions.scala
Labels: bug
