Repository hail-is/hail, pull requests merged in 2018-10, with the labels that each got.

#4546 promote y to column vector in from_random_effects
  hail/python/hail/stats/linear_mixed_model.py
Labels: bug, tiny PR

#4555 aggregator IR rework
  hail/python/hail/docs/tutorials/06-aggregation.ipynb
  hail/python/hail/expr/aggregators/__init__.py
  hail/python/hail/expr/aggregators/aggregators.py
  hail/python/hail/expr/expressions/__init__.py
  hail/python/hail/expr/expressions/base_expression.py
  hail/python/hail/expr/expressions/expression_utils.py
  hail/python/hail/ir/ir.py
  hail/python/hail/matrixtable.py
  hail/python/hail/methods/family_methods.py
  hail/python/hail/methods/qc.py
  hail/python/test/hail/experimental/test_experimental.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/methods/test_qc.py
  hail/python/test/hail/table/test_table.py
  hail/python/test/hail/test_ir.py
  hail/src/main/scala/is/hail/annotations/aggregators/KeyedRegionValueAggregator.scala
  hail/src/main/scala/is/hail/expr/Parser.scala
  hail/src/main/scala/is/hail/expr/ir/AggOp.scala
  hail/src/main/scala/is/hail/expr/ir/Binds.scala
  hail/src/main/scala/is/hail/expr/ir/Children.scala
  hail/src/main/scala/is/hail/expr/ir/CodeAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/Compile.scala
  hail/src/main/scala/is/hail/expr/ir/Copy.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/ExtractAggregators.scala
  hail/src/main/scala/is/hail/expr/ir/IR.scala
  hail/src/main/scala/is/hail/expr/ir/Infer.scala
  hail/src/main/scala/is/hail/expr/ir/Interpret.scala
  hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/Pretty.scala
  hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
  hail/src/main/scala/is/hail/expr/ir/Simplify.scala
  hail/src/main/scala/is/hail/expr/ir/Subst.scala
  hail/src/main/scala/is/hail/expr/ir/TableIR.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
  hail/src/test/scala/is/hail/TestUtils.scala
  hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
  hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
  hail/src/test/scala/is/hail/expr/ir/InterpretSuite.scala
  hail/src/test/scala/is/hail/expr/ir/TestUtils.scala
Labels: breaking change

#4590 update landing post-ASHG
  hail/www/landing.md
Labels: tiny PR

#4597 edit jobs page
  hail/www/jobs.md
  hail/www/landing.md
Labels: tiny PR

#4599 add GWASbot link
  hail/www/landing.md
Labels: tiny PR

#4623 Add secrets to scorecard gitignore
  scorecard/.gitignore
Labels: tiny PR

#4637 Remove the dependency of testCppCodegen from test
  hail/build.gradle
Labels: tiny PR
