Repository hail-is/hail, pull requests merged in 2019-12, with the labels that each got.

#7650 [ci] fix get_pr function to convert async generator to list
  ci/ci/ci.py
Labels: prio:high

#7596 [batch2] add billing project
  Makefile
  batch2/Dockerfile.tables
  batch2/batch/front_end/front_end.py
  batch2/batch/front_end/schemas.py
  batch2/create-batch-tables-pod.yaml
  batch2/create-batch-tables.sql
  batch2/create-billing-projects.sql
  batch2/delete-batch-tables.sql
  batch2/test/test_aioclient.py
  batch2/test/test_batch.py
  batch2/test/test_dag.py
  batch2/test/test_scale.py
  ci/ci/ci.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/hailtop/hailctl/batch/cli.py
  hail/python/hailtop/pipeline/backend.py
  pipeline/test/test_pipeline.py
Labels: prio:high

#7229 [hail] [streams] more complicated streams
  hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/Streamify.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
Labels: infrastructure

#7678 Add liblapack3 to base image
  ci/test/test_ci.py
  docker/Dockerfile.base
Labels: tiny PR

#7696 [hail] Remove unused Extract object.
  hail/src/main/scala/is/hail/expr/ir/Exists.scala
Labels: tiny PR

#7738 Release 0.2.29
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#7771 [hail] Fix EXTREME performance regression in column scans.
  benchmark/python/benchmark_hail/run/matrix_table_benchmarks.py
  hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
Labels: bug, performance, prio:high
