Repository hail-is/hail, pull requests merged in 2019-05, with the labels that each got.

#6007 [ci] aim: one complete build status for a tip source sha
  ci2/ci/github.py
  ci2/setup.cfg
Labels: prio:high

#6038 [ci2] build logic mark 2
  apiserver/deployment.yaml
  batch/deployment.yaml
  ci2/ci/ci.py
  ci2/ci/github.py
  ci2/deployment.yaml
  gateway/deployment.yaml.in
  image-fetcher/deployment.yaml
  notebook2/deployment.yaml
  pylintrc
  router-resolver/deployment.yaml.in
  router/deployment.yaml
  scorecard/deployment.yaml
  site/deployment.yaml
  vdc/priority-classes.yaml
Labels: prio:high

#6075 [batch] Cleanup pvc, job task, create pod
  batch/batch/server/server.py
  batch/create-batch-tables.sql
Labels: prio:high

#6110 [pipeline] get rid of hard coded service account
  apiserver/Dockerfile.hail-jupyter
  batch/batch/client.py
  batch/batch/server/server.py
  build.yaml
  hailjwt/hailjwt/hailjwt.py
  pipeline/pipeline/backend.py
  pipeline/pipeline/pipeline.py
  pipeline/pipeline/resource.py
  pipeline/pipeline/utils.py
  pipeline/test-pipeline-pod.yaml
  pipeline/test/test_pipeline.py
Labels: prio:high

#6160 [batch] change how exit codes are stored
  batch/batch/server/database.py
  batch/batch/server/server.py
  batch/create-batch-tables.sql
  batch/test/test_aioclient.py
  batch/test/test_batch.py
  batch/test/test_dag.py
  ci2/ci/templates/batch.html
  pipeline/pipeline/backend.py
Labels: prio:high

#6096 [bugfix] fix LoadVCF warning logic
  hail/src/main/scala/is/hail/io/vcf/LoadVCF.scala
Labels: tiny PR

#6113 [doc] fix typo in rbind docs
  hail/python/hail/expr/functions.py
Labels: tiny PR

#6140 Test jwt signing key
  apiserver/apiserver/apiserver.py
  apiserver/deployment.yaml
  apiserver/test-apiserver-pod.yaml
  batch/deployment.yaml
  batch/test-batch-pod.yaml
  build.yaml
  ci2/ci/build.py
  ci2/deployment.yaml
  notebook2/deployment.yaml
  notebook2/notebook/notebook.py
  pipeline/test-pipeline-pod.yaml
Labels: prio:high

#6172 [hail] [breaking] split_multi_hts: take previous GQ if PL is missing
  hail/python/hail/methods/statgen.py
Labels: breaking change

#6204 [hail] Lowered MatrixMultiWrite node
  hail/src/main/scala/is/hail/expr/ir/Children.scala
  hail/src/main/scala/is/hail/expr/ir/Copy.scala
  hail/src/main/scala/is/hail/expr/ir/IR.scala
  hail/src/main/scala/is/hail/expr/ir/InferType.scala
  hail/src/main/scala/is/hail/expr/ir/Interpret.scala
  hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/Parser.scala
  hail/src/main/scala/is/hail/expr/ir/Pretty.scala
  hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
  hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Labels: prio:high

#6203 batch: initialize jinja
  batch/batch/server/server.py
Labels: prio:high

#6209 [batch] jinja template can't be web response
  batch/batch/server/server.py
  batch/test/test_batch.py
Labels: prio:high
