Repository hail-is/hail, pull requests merged in 2019-11, with the labels that each got.

#7394 [hail] matrix table tail
  hail/python/hail/ir/matrix_ir.py
  hail/python/hail/matrixtable.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/src/main/scala/is/hail/expr/ir/LowerMatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/Parser.scala
  hail/src/main/scala/is/hail/expr/ir/Pretty.scala
  hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
  hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Labels: new-feature

#7452 [hail] make float parsing correspond more precisely to python semantics
  hail/python/test/hail/expr/test_expr.py
  hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
  hail/src/main/scala/is/hail/utils/richUtils/RichString.scala
Labels: enhancement, prio:low

#7453 [hail] variation of `hl.float`/`hl.int` that returns null on invalid string
  hail/python/hail/docs/functions/index.rst
  hail/python/hail/docs/functions/string.rst
  hail/python/hail/expr/__init__.py
  hail/python/hail/expr/functions.py
  hail/python/test/hail/expr/test_expr.py
  hail/src/main/scala/is/hail/expr/ir/functions/UtilFunctions.scala
Labels: new-feature

#7474 [batch,ci,pipeline] remove batch from build.yaml and tests
  batch/batch-pods-deployment.yaml
  batch2/test/test_aioclient.py
  batch2/test/test_batch.py
  batch2/test/test_dag.py
  benchmark/scripts/benchmark_in_pipeline.py
  build.yaml
  ci/ci/ci.py
  ci/default-admin-admin.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/hailtop/pipeline/backend.py
  pipeline/test/test_pipeline.py
  router/router.nginx.conf.in
  web_common/web_common/templates/header.html
  web_common/web_common/web_common.py
Labels: prio:high

#7501 [hail][ndarray] Better PNDArray._toPretty
  hail/src/main/scala/is/hail/expr/types/physical/PNDArray.scala
Labels: tiny PR

#7519 [hail] Don't log full IRs unintentionally
  hail/src/main/scala/is/hail/expr/ir/InterpretNonCompilable.scala
Labels: prio:high

#7598 [ci] fix CI leaking batch images
  batch2/batch/batch_configuration.py
  batch2/deployment.yaml
  ci/Makefile
  ci/ci/environment.py
Labels: prio:high

#7610 Document hail.version
  hail/python/hail/context.py
  hail/python/hail/docs/api.rst
Labels: tiny PR
