Repository hail-is/hail, pull requests merged in 2019-06, with the labels that each got.

#6302 [hail] Extend ExtractIntervalFilters to operate on key structs
  hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala
  hail/src/test/scala/is/hail/expr/ir/ExtractIntervalFiltersSuite.scala
Labels: stacked PR

#6321 turn off lowered compile except for tests
  hail/src/main/scala/is/hail/HailContext.scala
  hail/src/main/scala/is/hail/backend/Backend.scala
  hail/src/test/scala/is/hail/SparkSuite.scala
Labels: prio:high

#6331 [ci] fix ci deploy
  ci/ci/build.py
Labels: prio:high

#6353 [hail] [high-prio] Don't optimize in ApplyIR
  hail/src/main/scala/is/hail/expr/ir/IR.scala
Labels: prio:high

#6357 [ci] Fix makefile and site deploy
  hail/Makefile
  site/poll-0.2.sh
Labels: prio:high

#6402 [release] Update changelog for 0.2.16.
  hail/Makefile
  hail/build.gradle
  hail/python/hail/docs/change_log.md
Labels: prio:high

#6419 [hail][bugfix] Fix TableFilterIntervals/TableMapRows rewrite
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/Simplify.scala
Labels: prio:high

#6434 [hailjwt,ci] fix authorized sha csrf
  hailjwt/hailjwt/csrf.py
Labels: prio:high

#6418 [scheduler][bugfix-ish] add more logging, job tokens
  hail/src/main/scala/is/hail/scheduler/Client.scala
  hail/src/main/scala/is/hail/scheduler/package.scala
  hail/src/test/scala/is/hail/TestUtils.scala
  scheduler/scheduler/scheduler.py
  scheduler/templates/index.html
Labels: prio:high

#6366 [batch] increase storage limit to 100Ti / 100000
  batch/batch-pods-deployment.yaml
Labels: prio:high

#6508 [batch] sometimes pod metadata name is None
  batch/batch/batch.py
Labels: prio:high

#6499 add ability to get and clear sub-regions by index
  hail/prebuilt/lib/darwin/libboot.dylib
  hail/prebuilt/lib/darwin/libhail.dylib
  hail/prebuilt/lib/linux-x86-64/libboot.so
  hail/prebuilt/lib/linux-x86-64/libhail.so
  hail/src/main/c/Region.cpp
  hail/src/main/resources/include/hail/Region.h
  hail/src/main/scala/is/hail/annotations/Region.scala
  hail/src/main/scala/is/hail/utils/richUtils/RichCodeRegion.scala
  hail/src/test/scala/is/hail/annotations/UnsafeSuite.scala
Labels: aggregators

#6487 [batch] easy performance improvements
  batch/batch/batch.py
Labels: prio:high

#6512 [batch] back off on create pods loop
  batch/batch/batch.py
Labels: prio:high

#6502 create some IR nodes for new aggregation strategy
  hail/src/main/scala/is/hail/expr/ir/Children.scala
  hail/src/main/scala/is/hail/expr/ir/Copy.scala
  hail/src/main/scala/is/hail/expr/ir/IR.scala
  hail/src/main/scala/is/hail/expr/ir/InferType.scala
  hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
  hail/src/main/scala/is/hail/expr/ir/Parser.scala
  hail/src/main/scala/is/hail/expr/ir/Pretty.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
  hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
Labels: aggregators

#6500 implement deep copy in SRVB
  hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
  hail/src/main/scala/is/hail/expr/types/physical/PContainer.scala
  hail/src/test/scala/is/hail/annotations/StagedRegionValueSuite.scala
Labels: aggregators

#6522 [ci] fix deadlock if unauthorized PR is merge candidate
  ci/ci/github.py
Labels: prio:high

#6489 [batch] save pod status
  batch/batch/batch.py
  batch/batch/database.py
  batch/batch/k8s.py
  batch/batch/templates/batch.html
  batch/batch/templates/pod_status.html
  batch/create-batch-tables.sql
  batch/test/test_batch.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/hailtop/hailctl/batch/cli.py
  hail/python/hailtop/hailctl/batch/pod_status.py
Labels: prio:high
