Repository hail-is/hail, pull requests merged in 2020-01, with the labels that each got.

#7794 [hail] NDArrayMatMul Requiredness Fix
  hail/python/test/hail/expr/test_ndarrays.py
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
Labels: tiny PR

#7789 [hail] fix pruning in `hl.skat` by using select instead of annotate
  hail/python/hail/methods/statgen.py
Labels: tiny PR

#7885 [batch] change select for update to select lock in share mode
  batch/sql/add-lock-in-share-mode.sql
  build.yaml
Labels: migration

#7875 [batch] failure resilience on insert
  batch/batch/front_end/front_end.py
  batch/batch/front_end/schemas.py
  batch/sql/add-batch-create-token.sql
  batch/test/failure_injecting_client_session.py
  batch/test/test_batch.py
  build.yaml
  gear/gear/database.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/hailtop/pipeline/backend.py
Labels: migration, prio:high

#7902 [gear][batch] Retry-able Transactions
  batch/batch/front_end/front_end.py
  gear/gear/__init__.py
  gear/gear/database.py
Labels: prio:high

#7922 [hail] Write custom serializer for ApproxCDFCombiner to avoid issues
  hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFStateManager.scala
Labels: prio:high

#7933 [batch] improve cancel
  batch/batch/batch.py
  batch/batch/driver/main.py
  batch/batch/driver/scheduler.py
  batch/batch/front_end/front_end.py
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.txt
  batch/sql/improve-cancel.sql
  batch/utils/stress.py
  build.yaml
  hail/python/hailtop/pipeline/backend.py
  hail/python/hailtop/pipeline/task.py
Labels: migration

#7955 [batch] fix return value for run_if_changed
  batch/batch/driver/scheduler.py
Labels: prio:high

#7981 [batch] remove overscheduling
  batch/batch/driver/scheduler.py
Labels: prio:high

#7986 2d by 1d matmul fix
  hail/python/test/hail/expr/test_ndarrays.py
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
Labels: tiny PR

#7949 [batch] move spec, status to gcs
  batch/batch/batch.py
  batch/batch/batch_format_version.py
  batch/batch/driver/instance.py
  batch/batch/driver/main.py
  batch/batch/driver/scheduler.py
  batch/batch/driver/templates/index.html
  batch/batch/front_end/front_end.py
  batch/batch/globals.py
  batch/batch/google_storage.py
  batch/batch/log_store.py
  batch/batch/spec_writer.py
  batch/batch/worker.py
  batch/sql/add-batches-time-closed.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.txt
  batch/sql/store-specs-in-gcs.sql
  batch/test/test_batch.py
  batch/test/utils.py
  build.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
Labels: migration

#7993 [ci] fix ui attributes again
  ci/ci/ci.py
Labels: prio:high

#8002 [batch] add name to job json
  batch/batch/batch.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/batch.html
  ci/ci/templates/batch.html
  ci/ci/templates/pr.html
Labels: prio:high

#8014 [batch] Fix catch duplicate key
  batch/batch/front_end/front_end.py
Labels: prio:high

#8017 [batch] decrease instance creation rate
  batch/batch/driver/instance_pool.py
Labels: prio:high

#8022 [batch] fix scheduler -- schedule job timeout 1sec
  batch/batch/batch.py
Labels: prio:high
