Repository hail-is/hail, pull requests merged in 2020-03, with the labels that each got.

#8220 [batch] fix instance check when ip address is reused
  batch/batch/driver/instance.py
  batch/batch/worker.py
Labels: prio:high

#8225 [batch] stripe across region after 5k cores
  batch/batch/driver/instance_pool.py
Labels: prio:high

#8226 [batch] stripe across regions based on total cores
  batch/batch/driver/instance_pool.py
Labels: prio:high

#8142 [query/ptypes] ptypes are real
  hail/src/main/scala/is/hail/annotations/BroadcastValue.scala
  hail/src/main/scala/is/hail/annotations/RegionValueBuilder.scala
  hail/src/main/scala/is/hail/annotations/StagedRegionValueBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
  hail/src/main/scala/is/hail/expr/ir/Compile.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/IR.scala
  hail/src/main/scala/is/hail/expr/ir/InferPType.scala
  hail/src/main/scala/is/hail/expr/ir/InferType.scala
  hail/src/main/scala/is/hail/expr/ir/Interpret.scala
  hail/src/main/scala/is/hail/expr/ir/Optimize.scala
  hail/src/main/scala/is/hail/expr/ir/Simplify.scala
  hail/src/main/scala/is/hail/expr/ir/TableIR.scala
  hail/src/main/scala/is/hail/expr/ir/TableValue.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
  hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/Extract.scala
  hail/src/main/scala/is/hail/expr/ir/agg/StagedArrayBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/agg/StagedBlockLinkedList.scala
  hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LoweringPass.scala
  hail/src/main/scala/is/hail/expr/types/BaseType.scala
  hail/src/main/scala/is/hail/expr/types/BlockMatrixType.scala
  hail/src/main/scala/is/hail/expr/types/MatrixType.scala
  hail/src/main/scala/is/hail/expr/types/TableType.scala
  hail/src/main/scala/is/hail/expr/types/encoded/EType.scala
  hail/src/main/scala/is/hail/expr/types/physical/PBaseStruct.scala
  hail/src/main/scala/is/hail/expr/types/physical/PCanonicalArray.scala
  hail/src/main/scala/is/hail/expr/types/physical/PCanonicalBaseStruct.scala
  hail/src/main/scala/is/hail/expr/types/physical/PType.scala
  hail/src/main/scala/is/hail/expr/types/physical/PVoid.scala
  hail/src/main/scala/is/hail/expr/types/virtual/Type.scala
  hail/src/main/scala/is/hail/io/TextMatrixReader.scala
  hail/src/main/scala/is/hail/rvd/AbstractRVDSpec.scala
  hail/src/test/scala/is/hail/TestUtils.scala
  hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
  hail/src/test/scala/is/hail/expr/ir/AggregatorsSuite.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
  hail/src/test/scala/is/hail/expr/ir/OrderingSuite.scala
Labels: prio:high

#8242 [batch] run ci jobs only in us-central1
  batch/batch/driver/scheduler.py
Labels: prio:high

#8156 [query/streams] port more stream nodes
  hail/src/main/scala/is/hail/asm4s/joinpoint/ParameterPack.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
Labels: prio:high

#8253 Support Requester Pays
  hail/python/hailtop/hailctl/dataproc/start.py
Labels: prio:high

#8204 [query/streams] remaining non-root stream nodes, add back length tracking
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
  hail/src/test/scala/is/hail/expr/ir/Aggregators2Suite.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
Labels: prio:high

#8214 [query/streams] port stream producers, delete old EmitStream
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
Labels: prio:high

#8268 Move VEP to Requester Pays
  hail/Makefile
  hail/python/cluster-tests/cluster-vep-check-GRCh37.py
  hail/python/cluster-tests/cluster-vep-check-GRCh38.py
  hail/python/hail/methods/qc.py
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
  hail/python/hailtop/hailctl/dataproc/start.py
Labels: prio:high

#8360 [query] Add PLocus to PCode constructor match
  hail/src/main/scala/is/hail/expr/ir/PCode.scala
Labels: tiny PR

#8294 [batch] Add billing UI page
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/billing.html
  batch/sql/add-batches-time-created-index.sql
  batch/sql/estimated-current.txt
  build.yaml
  web_common/web_common/templates/header.html
Labels: migration
