Repository hail-is/hail, pull requests merged in 2020-09, with the labels that each got.

#9389 [monitoring] fix test to allow no data returned by big query
  monitoring/test/test_monitoring.py
Labels: prio:high

#9390 [batch] avoid use of metadata server in regenie tests
  hail/python/hailtop/batch/genetics/regenie/regenie.py
Labels: prio:high

#9228 Blanczos randomized PCA
  hail/python/hail/methods/__init__.py
  hail/python/hail/methods/pca.py
  hail/python/hail/methods/statgen.py
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/methods/test_statgen.py
Labels: new-feature

#9448 [batch] Fix billing_projects.html
  batch/batch/front_end/templates/billing_projects.html
Labels: prio:high

#9441 [batch] Change number test worker pool size
  batch/sql/change_test_worker_pool_size.py
  build.yaml
Labels: migration, prio:high

#9455 [query/sparse_mt] preserve phasing in lgt_to_gt
  hail/python/hail/experimental/vcf_combiner/sparse_mt_utils.py
Labels: tiny PR
