Repository hail-is/hail, pull requests merged in 2020-05, with the labels that each got.

#8689 [query] Fix bugs in encoding/decoding when requiredness doesn't match
  hail/src/main/scala/is/hail/expr/types/encoded/EArray.scala
  hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
  hail/src/main/scala/is/hail/io/MemoryBuffer.scala
  hail/src/test/scala/is/hail/expr/ir/ETypeSuite.scala
Labels: prio:high

#8693 [Query] Continue to replace Code[Unit] with CodeBuilder
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/EmitFunctionBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/agg/AggregatorState.scala
  hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
  hail/src/main/scala/is/hail/expr/ir/agg/ApproxCDFAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/ArrayElementLengthCheckAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/CallStatsAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/CollectAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/CollectAsSetAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/CountAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/DownsampleAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/GroupedAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/LinearRegressionAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/MonoidAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/PrevNonNullAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/StagedAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/TakeAggregator.scala
  hail/src/main/scala/is/hail/expr/ir/agg/TakeByAggregator.scala
  hail/src/main/scala/is/hail/lir/X.scala
  hail/src/test/scala/is/hail/expr/ir/FunctionSuite.scala
  hail/src/test/scala/is/hail/expr/ir/StagedBTreeSuite.scala
  hail/src/test/scala/is/hail/expr/ir/TakeByAggregatorSuite.scala
  hail/src/test/scala/is/hail/expr/ir/agg/DownsampleSuite.scala
Labels: spicy meatball

#8759 [batch] add resources to billing
  batch/batch/batch.py
  batch/batch/batch_format_version.py
  batch/batch/driver/instance_pool.py
  batch/batch/driver/main.py
  batch/batch/driver/scheduler.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/job.html
  batch/batch/globals.py
  batch/batch/log_store.py
  batch/batch/utils.py
  batch/batch/worker.py
  batch/batch/worker_config.py
  batch/sql/add-resources.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.txt
  batch/sql/insert_resources.py
  build.yaml
Labels: migration

#8838 Removed TypedAggregator
  hail/src/main/scala/is/hail/expr/package.scala
Labels: tiny PR

#8880 [query] don't search for block at the beginning of a bgzip file
  hail/src/main/java/is/hail/io/compress/BGzipInputStream.java
Labels: prio:high
