Repository hail-is/hail, pull requests merged in 2020-10, with the labels that each got.

#9525 Update all make in makefiles to use $(MAKE)
  Makefile
  address/Makefile
  admin-pod/Makefile
  auth/Makefile
  batch/Makefile
  benchmark-service/Makefile
  ci/Makefile
  docker/Makefile
  hail/Makefile
  hail/python/hail/docs/Makefile
  memory/Makefile
  monitoring/Makefile
  query/Makefile
  router-resolver/Makefile
  shuffler/Makefile
  site/Makefile
Labels: tiny PR

#9563 [scorecard] fix yaml
  scorecard/deployment.yaml
Labels: prio:high

#9574 [query] use a 10 minute timeout
  hail/python/hail/backend/service_backend.py
  hail/python/hailtop/utils/utils.py
  query/test/test_query.py
Labels: prio:high

#9354 [batch] Aggregated billing project resources infrastructure
  batch/batch/batch.py
  batch/batch/driver/main.py
  batch/batch/exceptions.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/billing_limits.html
  batch/sql/add-aggregated-billing-project-resources.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/test/test_accounts.py
  batch/test/test_batch.py
  build.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  web_common/web_common/templates/header.html
Labels: migration
