Repository hail-is/hail, pull requests merged in 2021-01, with the labels that each got.

#9844 [batch] make standing worker configurable in the UI
  batch/batch/batch_configuration.py
  batch/batch/driver/instance_pool.py
  batch/batch/driver/main.py
  batch/batch/driver/templates/index.html
  batch/deployment.yaml
  batch/sql/add-enable-standing-worker.py
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#9875 [batch] pass credentials for both GCR and Artifact Registry images
  batch/batch/worker/worker.py
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
Labels: prio:high

#9832 [batch] Add instance collections
  batch/batch/batch.py
  batch/batch/driver/canceller.py
  batch/batch/driver/create_instance.py
  batch/batch/driver/gce.py
  batch/batch/driver/instance.py
  batch/batch/driver/instance_collection.py
  batch/batch/driver/instance_collection_manager.py
  batch/batch/driver/instance_pool.py
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/batch/driver/pool.py
  batch/batch/driver/scheduler.py
  batch/batch/driver/templates/index.html
  batch/batch/driver/templates/pool.html
  batch/batch/driver/templates/user_resources.html
  batch/batch/driver/zone_monitor.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/pool_selector.py
  batch/batch/front_end/templates/batch.html
  batch/batch/front_end/validate.py
  batch/batch/globals.py
  batch/batch/utils.py
  batch/batch/worker/worker.py
  batch/deployment.yaml
  batch/sql/add-inst-colls.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/test/test_batch.py
  batch/test/test_dag.py
  batch/utils/stress.py
  build.yaml
  hail/python/hailtop/batch/docs/service.rst
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
Labels: migration

#9945 [router] dont log lines of startup script
  router/start-nginx.sh
Labels: tiny PR
