Repository hail-is/hail, pull requests merged in 2021-04, with the labels that each got.

#10258 [hailtop] add hailtop/hail_version to .gitignore
  hail/.gitignore
Labels: tiny PR

#10276 [ci] allow dev deploy to forcibly exclude build steps
  ci/ci/build.py
  ci/ci/ci.py
  ci/ci/github.py
  hail/python/hailtop/hailctl/dev/deploy/cli.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
Labels: spicy meatball

#10292 [notebook] fix notebook service to expose nginx and use http with workers
  notebook/deployment.yaml
  notebook/nginx.conf
Labels: prio:high

#10285 [dataproc] Update sparkmonitor to version that supports spark 3
  hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Labels: prio:high

#10229 [query] New stream design
  hail/python/hail/ir/ir.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/src/main/scala/is/hail/asm4s/Code.scala
  hail/src/main/scala/is/hail/asm4s/joinpoint/JoinPoint.scala
  hail/src/main/scala/is/hail/asm4s/joinpoint/package.scala
  hail/src/main/scala/is/hail/expr/ir/Children.scala
  hail/src/main/scala/is/hail/expr/ir/Compile.scala
  hail/src/main/scala/is/hail/expr/ir/Copy.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/EmitClassBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/EmitCodeBuilder.scala
  hail/src/main/scala/is/hail/expr/ir/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/GenericTableValue.scala
  hail/src/main/scala/is/hail/expr/ir/IR.scala
  hail/src/main/scala/is/hail/expr/ir/InferPType.scala
  hail/src/main/scala/is/hail/expr/ir/InferStreamMemoryManagement.scala
  hail/src/main/scala/is/hail/expr/ir/InferType.scala
  hail/src/main/scala/is/hail/expr/ir/Interpret.scala
  hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
  hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
  hail/src/main/scala/is/hail/expr/ir/Parser.scala
  hail/src/main/scala/is/hail/expr/ir/Pretty.scala
  hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
  hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
  hail/src/main/scala/is/hail/expr/ir/Simplify.scala
  hail/src/main/scala/is/hail/expr/ir/StagedRegion.scala
  hail/src/main/scala/is/hail/expr/ir/TableIR.scala
  hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
  hail/src/main/scala/is/hail/expr/ir/agg/AppendOnlyBTree.scala
  hail/src/main/scala/is/hail/expr/ir/package.scala
  hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala
  hail/src/main/scala/is/hail/expr/ir/streams/StreamUtils.scala
  hail/src/main/scala/is/hail/types/physical/PCanonicalArray.scala
  hail/src/main/scala/is/hail/types/physical/PCanonicalStream.scala
  hail/src/main/scala/is/hail/types/physical/PCode.scala
  hail/src/main/scala/is/hail/types/physical/PStream.scala
  hail/src/main/scala/is/hail/types/physical/package.scala
  hail/src/main/scala/is/hail/types/physical/stypes/SType.scala
  hail/src/main/scala/is/hail/types/physical/stypes/concrete/SSubsetStruct.scala
  hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SContainer.scala
  hail/src/main/scala/is/hail/types/physical/stypes/interfaces/SStream.scala
  hail/src/main/scala/is/hail/utils/richUtils/RichCodeRegion.scala
  hail/src/test/scala/is/hail/expr/ir/EmitStreamSuite.scala
  hail/src/test/scala/is/hail/expr/ir/IRSuite.scala
  hail/src/test/scala/is/hail/expr/ir/PruneSuite.scala
Labels: spicy meatball

#10319 Release 0.2.65
  hail/Makefile
  hail/python/cluster-tests/cluster-start-stop.py
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
Labels: prio:high

#10362 [hailctl] fix dataproc
  hail/python/hailtop/hailctl/dataproc/start.py
Labels: prio:high

#10367 [batch] avoid unnecessary locks
  batch/sql/do-not-lock-entire-batch.sql
  batch/sql/estimated-current.sql
  batch/test/test_batch.py
  build.yaml
Labels: migration

#10410 [batch] fix public gcr images
  batch/batch/worker/worker.py
Labels: prio:high

#10397 [batch] fail fast
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/validate.py
  batch/sql/add-fail-fast.sql
  batch/sql/estimated-current.sql
  build.yaml
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/batch/batch.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/test/hailtop/batch/test_batch.py
Labels: migration
