Repository hail-is/hail, pull requests merged in 2021-02, with the labels that each got.

#9985 [datasets] remove gnomad_annotation_pext
  hail/python/hail/docs/datasets/schemas/gnomad_annotation_pext.rst
  hail/python/hail/experimental/datasets.json
  hail/python/hail/experimental/datasets.py
Labels: prio:high

#9984 [release] Update changelog for 0.2.62.
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#9988 [pip] fix conflicting pip requirements between query and services
  docker/requirements.txt
Labels: tiny PR

#10036 [batch] Fix bug in schedule_job
  batch/sql/estimated-current.sql
  batch/sql/fix-schedule-job.sql
  build.yaml
Labels: migration, prio:high

#10063 [batch] Fix slow /batches query
  batch/batch/front_end/front_end.py
Labels: prio:high

#10065 [batch] Add limit to list_batches in tests
  batch/test/test_accounts.py
  batch/test/test_batch.py
Labels: prio:high

#10076 [batch] Fix issue when computing compatible resources
  batch/batch/inst_coll_config.py
Labels: prio:high

#10088 [query-service] remove flaky test code
  query/test/test_query.py
Labels: prio:high

#10096 [batch] Fix create billing projects in UI
  batch/batch/front_end/front_end.py
Labels: prio:high
