Repository hail-is/hail, pull requests merged in 2022-08, with the labels that each got.

#12078 [batch] Use region requirements when choosing a location
  batch/batch/cloud/azure/driver/driver.py
  batch/batch/cloud/azure/driver/regions.py
  batch/batch/cloud/azure/instance_config.py
  batch/batch/cloud/gcp/driver/driver.py
  batch/batch/cloud/gcp/driver/zones.py
  batch/batch/cloud/gcp/instance_config.py
  batch/batch/driver/instance.py
  batch/batch/driver/instance_collection/base.py
  batch/batch/driver/instance_collection/job_private.py
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/location.py
  batch/batch/instance_config.py
Labels: prio:high

#11996 [batch] Add billing tables partitioned by date
  batch/batch/driver/main.py
  batch/sql/add-agg-billing-by-date.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/sql/populate_agg_billing_by_date.py
  build.yaml
Labels: prio:high, migration

#12081 [batch] Dont use tls for Azure pricing API
  hail/python/hailtop/aiocloud/aioazure/client/pricing_client.py
Labels: prio:high

#12006 [batch] Revert infrastructure for populating agg-by-date tables
  batch/sql/estimated-current.sql
  batch/sql/revert-temp-agg-by-date-infra.sql
  build.yaml
Labels: prio:high, migration

#12100 [batch] Rename billing_timestamp to billing_date in agg billing
  batch/sql/estimated-current.sql
  batch/sql/rename-timestamp-to-date.sql
  build.yaml
Labels: migration

#11997 [batch] Use the new aggregated by date billing tables
  batch/batch/batch.py
  batch/batch/batch_format_version.py
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/utils.py
Labels: prio:high

#11998 [batch] Add real time billing!
  batch/batch/driver/main.py
  batch/batch/worker/worker.py
  batch/sql/add-real-time-billing.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12148 Revert "[auth] Cache user sessions in memory"
  auth/auth/auth.py
  auth/deployment.yaml
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  benchmark-service/benchmark/benchmark.py
  ci/ci/ci.py
  gear/gear/__init__.py
  gear/gear/auth.py
  memory/memory/memory.py
  monitoring/monitoring/monitoring.py
  notebook/notebook/notebook.py
  website/website/website.py
Labels: prio:high
