Repository hail-is/hail, pull requests merged in 2022-07, with the labels that each got.

#11991 [deploy] fix releases
  hail/scripts/deploy.sh
Labels: prio:high

#11994 [release] 0.2.97
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#12005 [batch] Remove redundant env variable for internal gateway ip
  batch/deployment.yaml
Labels: tiny PR

#12049 [batch] Explicitly use index in get_batches query
  batch/batch/front_end/front_end.py
Labels: prio:high

#12043 [ci] Use 4 cores for db migration jobs in deploys
  ci/ci/build.py
Labels: prio:high

#12036 [ci] Add frozen mode and only merge if no active deploys
  build.yaml
  ci/ci/ci.py
  ci/ci/github.py
  ci/ci/templates/index.html
  ci/sql/add-frozen-mode.sql
  ci/sql/delete-ci-tables.sql
  ci/sql/estimated-current.sql
Labels: prio:high

#12028 [batch] Add resource ids to the attempt resources table
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/sql/add-resource-ids.sql
  batch/sql/add_resource_ids.py
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12029 [batch] Modify attempt resources trigger to prepare for future migrations
  batch/batch/driver/job.py
  batch/sql/estimated-current.sql
  batch/sql/modify-resource-id-trigger.sql
  build.yaml
Labels: migration

#12055 [batch] Fix bad /batches query again
  batch/batch/front_end/front_end.py
Labels: prio:high

#12053 [batch] Switch attempt resources primary keys and triggers to use resource ids
  batch/sql/estimated-current.sql
  batch/sql/rm-resource-foreign-keys.py
  batch/sql/rm-resource-names-agg-resources.sql
  build.yaml
Labels: prio:high, migration

#12030 [batch] Remove resource names from the attempt resources table
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/sql/rm-resource-names-agg-resources-pt-2.sql
  build.yaml
Labels: prio:high, migration

#11990 [batch] Add attempts with format version < 3 into attempt_resources
  batch/batch/instance_config.py
  batch/sql/add-att-resources-format-version-lt-3.sql
  batch/sql/estimated-current.sql
  batch/sql/insert_attempt_resources_format_version_lt_3.py
  build.yaml
Labels: prio:high, migration

#11995 [batch] Undo trigger change to ignore updates for format_version < 3
  batch/sql/estimated-current.sql
  batch/sql/revert-attempt-resources-trigger-back-compat.sql
  build.yaml
Labels: prio:high, migration
