Repository hail-is/hail, pull requests merged in 2022-03, with the labels that each got.

#11434 Always Exclude Spark from Build
  hail/build.gradle
Labels: prio:high

#11442 [build.yaml] steps using tokens need to depend on create-accounts
  build.yaml
Labels: prio:high

#11441 [build.yaml] steps using database-server-config must depend on its creation
  build.yaml
Labels: prio:high

#11448 [batch] mitigate some of the cost test failures
  batch/test/test_accounts.py
Labels: prio:high

#11420 [batch] Mitigate accrued_costs test failure
  batch/test/test_accounts.py
Labels: prio:high

#11489 [build.yaml] Fix dependencies on Memory
  build.yaml
Labels: prio:high

#11387 [compiler] lowered TableIntervalJoin
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/methods/test_misc.py
  hail/python/test/hail/table/test_table.py
  hail/python/test/hail/vds/test_vds.py
  hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Labels: prio:high

#11481 [dependabot] python package updates omnibus
  auth/auth/driver/driver.py
  auth/auth/flow.py
  batch/batch/cloud/azure/driver/driver.py
  batch/batch/cloud/azure/driver/regions.py
  batch/batch/cloud/azure/resource_utils.py
  batch/batch/cloud/azure/worker/worker_api.py
  batch/batch/cloud/gcp/driver/zones.py
  batch/batch/cloud/gcp/resource_utils.py
  batch/batch/cloud/gcp/worker/worker_api.py
  batch/batch/cloud/resource_utils.py
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/worker/worker.py
  benchmark-service/benchmark/benchmark.py
  ci/ci/build.py
  ci/ci/ci.py
  ci/ci/github.py
  docker/requirements.txt
  gear/gear/cloud_config.py
  gear/gear/database.py
  hail/python/dev/requirements.txt
  hail/python/hail/fs/hadoop_fs.py
  hail/python/hailtop/aiocloud/aioazure/credentials.py
  hail/python/hailtop/aiocloud/aioazure/fs.py
  hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py
  hail/python/hailtop/aiocloud/aiogoogle/credentials.py
  hail/python/hailtop/auth/sql_config.py
  hail/python/hailtop/auth/tokens.py
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/batch/batch.py
  hail/python/hailtop/batch/conftest.py
  hail/python/hailtop/batch/docker.py
  hail/python/hailtop/batch/job.py
  hail/python/hailtop/batch/resource.py
  hail/python/hailtop/batch/utils.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/config/deploy_config.py
  hail/python/hailtop/config/user_config.py
  hail/python/hailtop/dictfix.py
  hail/python/hailtop/hail_logging.py
  hail/python/hailtop/hailctl/__main__.py
  hail/python/hailtop/hailctl/config/cli.py
  hail/python/hailtop/hailctl/dataproc/cluster_config.py
  hail/python/hailtop/hailctl/dataproc/connect.py
  hail/python/hailtop/hailctl/dataproc/diagnose.py
  hail/python/hailtop/hailctl/describe.py
  hail/python/hailtop/hailctl/dev/config/set_property.py
  hail/python/hailtop/httpx.py
  hail/python/hailtop/tls.py
  hail/python/hailtop/utils/validate/validate.py
  hail/python/requirements.txt
  memory/memory/memory.py
  pylintrc
Labels: prio:high

#11345 [vds] Fix and test `hl.vds.filter_intervals`
  hail/python/hail/vds/methods.py
  hail/python/test/hail/vds/test_vds.py
Labels: prio:high

#11499 [dependabot] weekly instead of once a daily
  .github/dependabot.yml
Labels: prio:high

#11482 [omnibus] grouping a bunch of approved likely passing changes together
  .git-blame-ignore-revs
  batch/batch/driver/main.py
  batch/batch/worker/worker.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/vds/variant_dataset.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
  hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
Labels: prio:high

#11552 [batch] fix flaky test
  batch/batch/worker/worker.py
  batch/test/test_batch.py
Labels: prio:high

#11611 Fix hline and vline not appearing
  build.yaml
  hail/python/hail/ggplot/ggplot.py
Labels: prio:high

#11615 release 0.2.91
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#11635 [query/service] fix calculation of number of flags
  hail/python/hail/backend/service_backend.py
Labels: prio:high

#11597 [query/service] implement index_bgen
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/local_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/backend/spark_backend.py
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
Labels: prio:high

#11622 [hailtop/utils] Allow OnlineBoundedGather2.call to return values
  hail/python/hail/fs/router_fs.py
  hail/python/hailtop/utils/utils.py
Labels: prio:high

#10792 Import table
  benchmark/python/benchmark_hail/run/table_benchmarks.py
  hail/python/hail/expr/expressions/typed_expressions.py
  hail/python/hail/ir/register_functions.py
  hail/python/hail/ir/table_reader.py
  hail/python/hail/ir/utils.py
  hail/python/hail/methods/impex.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/asm4s/Code.scala
  hail/src/main/scala/is/hail/expr/ir/SpecializedArrayBuilders.scala
  hail/src/main/scala/is/hail/expr/ir/StringTableReader.scala
  hail/src/main/scala/is/hail/expr/ir/TableIR.scala
  hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
  hail/src/main/scala/is/hail/expr/ir/functions/StringFunctions.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
  hail/src/main/scala/is/hail/io/TextMatrixReader.scala
  hail/src/main/scala/is/hail/utils/TextTableReader.scala
  hail/src/test/scala/is/hail/utils/TextTableSuite.scala
Labels: prio:high

#11642 [query] Actually allow the service to use the shuffler
  build.yaml
  hail/python/hail/backend/service_backend.py
  hail/src/main/scala/is/hail/HailFeatureFlags.scala
  hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/expr/ir/TableIR.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerDistributedSort.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
  hail/src/test/scala/is/hail/expr/ir/lowering/LowerDistributedSortSuite.scala
Labels: prio:high, qb28

#11636 [infra] Update k8s to 8-core nodes
  dev-docs/kubernetes-operations.md
  infra/azure/main.tf
  infra/azure/modules/batch/main.tf
  infra/azure/modules/ci/main.tf
  infra/azure/modules/vdc/main.tf
  infra/azure/modules/vdc/variables.tf
  infra/azure/variables.tf
  infra/gcp/main.tf
Labels: qb28

#11638 [batch] Use nginx reverse proxy to terminate TLS for batch-driver
  batch/Dockerfile.driver-nginx
  batch/Makefile
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/batch/spec_writer.py
  batch/deployment.yaml
  batch/driver-nginx.conf
  build.yaml
  gear/gear/database.py
  gear/gear/metrics.py
  hail/python/hailtop/utils/utils.py
  internal-gateway/internal-gateway.nginx.conf
  tls/config.yaml
Labels: prio:high, qb28

#11645 [query/service] automatically determine JAR url based on SHA
  batch/batch/front_end/front_end.py
  batch/batch/front_end/validate.py
  batch/batch/worker/worker.py
  batch/deployment.yaml
  build.yaml
  hail/.gitignore
  hail/Makefile
  hail/python/hail/__init__.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/context.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/setup.py
  hail/src/main/scala/is/hail/backend/service/Main.scala
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/backend/service/Worker.scala
  query/Makefile
Labels: qb28

#11396 [batch] Refactor worker Container class into Image and Container
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  hail/python/hailtop/aiotools/copy.py
Labels: qb28

#11624 [query/service] use error id to raise user-friendly errors
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/py4j_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/expr/test_ndarrays.py
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/methods/test_misc.py
  hail/python/test/hail/utils/test_utils.py
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/backend/service/Worker.scala
  hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
  hail/src/main/scala/is/hail/utils/ErrorHandling.scala
  hail/src/main/scala/is/hail/utils/richUtils/RichContextRDD.scala
Labels: qb28

#11669 [query/local] ensure init preserves the backend
  hail/python/hail/backend/local_backend.py
  hail/python/hail/context.py
  hail/python/hail/utils/java.py
  hail/python/test/hail/experimental/test_experimental.py
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/methods/relatedness/test_pc_relate.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/methods/test_statgen.py
  hail/python/test/hail/stats/test_linear_mixed_model.py
  hail/python/test/hail/test_context.py
  hail/python/test/hail/vds/test_combiner.py
  hail/src/main/scala/is/hail/io/plink/LoadPlink.scala
Labels: prio:high, qb28

#11656 [query] Replace ExportVCF.apply with lowered version
  hail/python/test/hail/methods/test_impex.py
  hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
  hail/src/main/scala/is/hail/io/vcf/ExportVCF.scala
Labels: qb28

#11676 [release] 0.2.92
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: qb28

#11673 [query] Support _filter_partitions in lowering
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Labels: qb28

#11397 [batch] Containerize the JVM
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/job.html
  batch/batch/worker/worker.py
  hail/python/test/hail/table/test_table.py
Labels: qb28

#11647 [query] lower import_matrix_table
  build.yaml
  hail/python/hail/expr/expressions/typed_expressions.py
  hail/python/hail/fs/fs.py
  hail/python/hail/fs/hadoop_fs.py
  hail/python/hail/fs/local_fs.py
  hail/python/hail/fs/router_fs.py
  hail/python/hail/ir/__init__.py
  hail/python/hail/ir/matrix_reader.py
  hail/python/hail/ir/table_reader.py
  hail/python/hail/methods/impex.py
  hail/python/hail/table.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/GenericLines.scala
  hail/src/main/scala/is/hail/expr/ir/MatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/StringTableReader.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
  hail/src/main/scala/is/hail/io/TextMatrixReader.scala
  hail/src/test/resources/sampleheaderdiffelem.txt
  hail/src/test/resources/samplenonintentries.txt
  hail/src/test/scala/is/hail/io/compress/BGzipCodecSuite.scala
Labels: qb28

#11620 [query/service] implement the function registry in the ServiceBackend
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/py4j_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/expr/types.py
  hail/python/test/hail/experimental/test_experimental.py
  hail/python/test/hail/expr/test_expr.py
  hail/python/test/hail/ggplot/test_ggplot.py
  hail/python/test/hail/methods/test_family_methods.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/methods/test_misc.py
  hail/python/test/hail/methods/test_pca.py
  hail/python/test/hail/methods/test_qc.py
  hail/python/test/hail/methods/test_statgen.py
  hail/python/test/hail/table/test_table.py
  hail/python/test/hail/test_context.py
  hail/python/test/hail/vds/test_vds.py
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/expr/ir/functions/Functions.scala
Labels: qb28

#11678 [query] Fix memory not being resolved in default
  letsencrypt/subdomains.txt
Labels: prio:high

#11677 [query/service] fast path for checkpoint and persist
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/experimental/expressions.py
  hail/python/hail/ir/matrix_ir.py
  hail/python/hail/ir/table_ir.py
  hail/python/hail/matrixtable.py
  hail/python/hail/methods/impex.py
  hail/python/hail/table.py
  hail/python/hail/utils/misc.py
Labels: qb28

#11637 [query] Lowered BlockMatrixBinaryReader and BlockMatrixBinaryWriter
  hail/python/hail/linalg/blockmatrix.py
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/methods/test_statgen.py
  hail/python/test/hail/stats/test_linear_mixed_model.py
  hail/src/main/scala/is/hail/expr/ir/BlockMatrixIR.scala
  hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerBlockMatrixIR.scala
  hail/src/main/scala/is/hail/types/encoded/ENumpyBinaryNDArray.scala
  hail/src/test/scala/is/hail/expr/ir/BlockMatrixIRSuite.scala
  hail/src/test/scala/is/hail/expr/ir/lowering/BlockMatrixStageSuite.scala
Labels: qb28

#11665 [query] Support repartition on lowered backends
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/local_backend.py
  hail/python/hail/backend/py4j_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/backend/spark_backend.py
  hail/python/hail/ir/matrix_reader.py
  hail/python/hail/ir/table_reader.py
  hail/python/hail/ir/utils.py
  hail/python/hail/matrixtable.py
  hail/python/hail/methods/impex.py
  hail/python/hail/table.py
  hail/python/hail/vds/variant_dataset.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/functions/RelationalFunctions.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/CanLowerEfficiently.scala
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
  hail/src/main/scala/is/hail/expr/ir/package.scala
Labels: qb28

#11672 [query] warn on using randomness on lowered backends
  hail/python/hail/ir/ir.py
Labels: qb28

#11675 [batch,query] Enable 8 core drivers with standard or highmem workers
  batch/batch/front_end/front_end.py
  batch/batch/worker/worker.py
  hail/python/hail/backend/service_backend.py
  hail/python/test/hail/backend/__init__.py
  hail/python/test/hail/backend/test_service_backend.py
  hail/python/test/hail/helpers.py
Labels: qb28

#11368 [batch] Save job memory and CPU statistics
  batch/batch/file_store.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/job.html
  batch/batch/resource_usage.py
  batch/batch/worker/worker.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/time.py
Labels: qb28

#11686 [batch] Fix errors on the worker
  batch/batch/worker/worker.py
Labels: qb28

#11670 [query/service] enable collecting 10 million rows
  hail/python/hail/backend/service_backend.py
  hail/python/hail/ir/base_ir.py
  hail/python/hail/ir/blockmatrix_writer.py
  hail/python/hail/ir/ir.py
  hail/python/test/hail/backend/test_service_backend.py
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/expr/ir/BlockMatrixWriter.scala
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/InferType.scala
  hail/src/main/scala/is/hail/expr/ir/Requiredness.scala
  hail/src/main/scala/is/hail/expr/ir/TypeCheck.scala
Labels: qb28

#11684 [query] propagate type information when we have it in BlockMatrix
  hail/python/hail/ir/blockmatrix_ir.py
  hail/python/hail/linalg/blockmatrix.py
Labels: qb28

#11685 [query/service] add docs, use consistent branding
  build.yaml
  hail/python/hail/__init__.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/context.py
  hail/python/hail/docs/cloud/query_on_batch.rst
  hail/python/hail/docs/hail_on_the_cloud.rst
  hail/python/hail/utils/java.py
  hail/python/test/hail/helpers.py
  hail/python/test/hail/methods/test_statgen.py
  query/Makefile
Labels: prio:high, qb28

#11688 [query/service] fixes for large pipelines
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/backend/service/Worker.scala
  hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
Labels: prio:high, qb28

#11680 [release] 0.2.93
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high, qb28

#11697 [black] Upgrade to 22.3.0
  docker/requirements.txt
  hail/python/dev/requirements.txt
Labels: prio:high
