Repository hail-is/hail, pull requests merged in 2022-06, with the labels that each got.

#11881 [ci] Fix upload_query_jar azure credentials
  build.yaml
Labels: prio:high

#11853 [local] Local backend always uses new shuffle
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/src/main/scala/is/hail/backend/local/LocalBackend.scala
  hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
Labels: prio:high

#11920 [query] nCombines calculation in tree aggregate
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Labels: prio:high

#11924 [memory] ensure we timeout requests
  hail/src/main/scala/is/hail/services/Requester.scala
Labels: prio:high

#11917 [hailtop] add retry once errors
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
Labels: prio:high

#11928 [batch] enable 5 JP instances in tests and alleviate failures
  batch/sql/set-test-and-dev-jpim-to-max-5.py
  build.yaml
Labels: prio:high

#11905 [fs] not FileNotFoundError for glob patterns
  hail/python/hail/fs/router_fs.py
  hail/python/test/hail/utils/test_utils.py
Labels: prio:high

#11906 [query] use one test per old file in file format test
  hail/python/test/hail/matrixtable/test_file_formats.py
Labels: prio:high

#11932 remove debugging print from test_vcf_parallel_separate_header_export
  hail/python/test/hail/methods/test_impex.py
Labels: tiny PR

#11919 [query/services] retry Azure errors
  hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#11933 [query] avoid rare test collection bug
  hail/python/test/hail/matrixtable/test_file_formats.py
Labels: prio:high

#11847 [query] python side infrastructure for deterministic rngs
  hail/python/hail/backend/local_backend.py
  hail/python/hail/backend/py4j_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/backend/spark_backend.py
  hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
  hail/python/hail/expr/aggregators/aggregators.py
  hail/python/hail/expr/expressions/typed_expressions.py
  hail/python/hail/expr/functions.py
  hail/python/hail/expr/types.py
  hail/python/hail/ir/__init__.py
  hail/python/hail/ir/base_ir.py
  hail/python/hail/ir/blockmatrix_ir.py
  hail/python/hail/ir/ir.py
  hail/python/hail/ir/matrix_ir.py
  hail/python/hail/ir/renderer.py
  hail/python/hail/ir/table_ir.py
  hail/python/hail/ir/utils.py
  hail/python/hail/matrixtable.py
  hail/python/hail/methods/qc.py
  hail/python/hail/table.py
  hail/python/hail/vds/combiner/combine.py
  hail/python/test/hail/test_ir.py
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
  hail/src/main/scala/is/hail/expr/ir/Interpretable.scala
  hail/src/main/scala/is/hail/expr/ir/Optimize.scala
  hail/src/main/scala/is/hail/expr/ir/Parser.scala
  hail/src/main/scala/is/hail/rvd/RVD.scala
Labels: spicy meatball

#11937 [query] Fix key pruning bug with respect to table/matrix row scans.
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/PruneDeadFields.scala
Labels: prio:high

#11955 Release 0.2.96
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#11956 Fix update_terra_image_py assignment in deploy.sh
  hail/scripts/deploy.sh
Labels: prio:high

#11968 Revert "[batch] Reattempt adding resource usage plots"
  batch/batch/file_store.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/job.html
  batch/batch/resource_usage.py
  batch/batch/worker/worker.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/time.py
Labels: prio:high

#11987 [QoB] disable import_plink using tests
  hail/python/test/hail/experimental/test_experimental.py
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/methods/test_king.py
Labels: prio:high
