Repository hail-is/hail, pull requests merged in 2022-10, with the labels that each got.

#12257 [batch] Add special-casing for Artifact Registry access denied message
  batch/batch/worker/worker.py
  build.yaml
  hail/python/hailtop/utils/utils.py
  hail/python/test/hailtop/batch/test_batch.py
  hail/python/test/hailtop/batch/test_batch_pool_executor.py
Labels: prio:high

#12259 [batch] Fix idempotent update-fast
  batch/batch/front_end/front_end.py
Labels: prio:high

#12256 [build.yaml] Make the deploy step work with AR
  build.yaml
Labels: prio:high

#12264 [release] update changelog for 0.2.101
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#12262 [lowering] Remove uses of RVDToTableStage in matrix writers
  hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
Labels: tiny PR

#12266 [deploy] Switch deploy to use artifact registry
  benchmark-service/benchmark/submit.py
  hail/scripts/deploy.sh
Labels: prio:high

#12277 [query] Correctly return first key in index if query compares less
  hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala
Labels: prio:high

#12279 [release] update changelog for 0.2.102
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#12281 [compiler] fix staged index reader
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala
Labels: prio:high

#12287 [docker] Build service images for x86
  docker-build.sh
Labels: tiny PR

#12304 [query] Add `_with_flags` context manager
  hail/python/hail/__init__.py
  hail/python/hail/context.py
Labels: prio:high

#12305 [query] Redesign staged index reading to compute index then query by index
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/HailFeatureFlags.scala
  hail/src/main/scala/is/hail/expr/ir/MatrixWriter.scala
  hail/src/main/scala/is/hail/expr/ir/TableWriter.scala
  hail/src/main/scala/is/hail/io/index/IndexWriter.scala
  hail/src/main/scala/is/hail/io/index/StagedIndexReader.scala
Labels: prio:high

#12221 [batch] Add support for job regions
  batch/batch/cloud/azure/driver/driver.py
  batch/batch/cloud/azure/driver/regions.py
  batch/batch/cloud/gcp/driver/driver.py
  batch/batch/cloud/gcp/driver/zones.py
  batch/batch/driver/exceptions.py
  batch/batch/driver/instance_collection/base.py
  batch/batch/driver/instance_collection/job_private.py
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/job.py
  batch/batch/driver/location.py
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/validate.py
  batch/batch/utils.py
  batch/sql/add-job-regions.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  build.yaml
  ci/ci/build.py
  ci/ci/environment.py
  hail/python/hailtop/batch/__init__.py
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/batch/batch.py
  hail/python/hailtop/batch/docs/service.rst
  hail/python/hailtop/batch/job.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/test/hailtop/batch/test_batch.py
Labels: prio:high

#12348 [compiler] remove stray println
  hail/src/main/scala/is/hail/expr/ir/Emit.scala
Labels: prio:high

#12340 [release] update changelog for 0.2.103
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
Labels: prio:high

#12346 [qob][batch] replace tqdm with rich
  batch/test/test_accounts.py
  docker/linux-pinned-requirements.txt
  docker/requirements.txt
  hail/python/dev/pinned-requirements.txt
  hail/python/hail/backend/service_backend.py
  hail/python/hailtop/aiotools/copy.py
  hail/python/hailtop/aiotools/delete.py
  hail/python/hailtop/aiotools/diff.py
  hail/python/hailtop/aiotools/utils.py
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/config/user_config.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/rich_progress_bar.py
  hail/python/hailtop/utils/tqdm.py
  hail/python/pinned-requirements.txt
  hail/python/requirements.txt
Labels: prio:high

#12353 [release] 0.2.104
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#12350 [batch] Add indices for faster pool scheduling
  batch/batch/driver/instance_collection/pool.py
  batch/sql/estimated-current.sql
  batch/sql/faster-regions-pool-scheduler.sql
  build.yaml
Labels: migration

#12094 [k8s] Move to headless services and make pods listen on 443
  auth/auth/auth.py
  auth/deployment.yaml
  batch/batch/front_end/front_end.py
  batch/deployment.yaml
  gateway/gateway.nginx.conf
  grafana/nginx.conf
  prometheus/nginx.conf
Labels: prio:high

#12367 [nginx] Fully specify in-cluster domain
  gateway/gateway.nginx.conf
  grafana/nginx.conf
  prometheus/nginx.conf
  prometheus/prometheus.yaml
Labels: prio:high

#12373 [ci] Consolidate check services steps
  Makefile
  build.yaml
Labels: tiny PR

#12374 [batch] Don't error if no regions are in the database on startup
  batch/batch/front_end/front_end.py
Labels: prio:high

#12351 [batch] Add index on batches.state
  batch/sql/add-batch-state-index.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12388 [qob] Add 429 to retryable status codes
  hail/python/hailtop/utils/utils.py
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#12392 Fixes for envoy
  batch/test/test_batch.py
  ci/ci/ci.py
  ci/ci/envoy.py
Labels: prio:high
