Repository hail-is/hail, pull requests merged in 2022-09, with the labels that each got.

#12152 [batch] Do not retry pulling images from invalid repositories
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  hail/python/hailtop/utils/utils.py
Labels: prio:high

#12179 [query] Fix FilterIntervals simplify rule
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/Simplify.scala
Labels: prio:high

#12164 [query] Allow seeks more than MAX_INT bytes away
  hail/src/main/scala/is/hail/io/fs/FS.scala
  hail/src/test/scala/is/hail/fs/FSSuite.scala
Labels: bug

#12189 [docker] Delete unused file and gitignore
  .gitignore
  docker/stat-permissions.sh
Labels: tiny PR

#12117 [batch] Add infrastructure for updates
  batch/batch/front_end/front_end.py
  batch/sql/add-batch-updates.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/sql/populate_batch_updates.py
  build.yaml
Labels: migration, full-deploy

#12193 [batch] Cleanup adding update id infrastructure
  batch/sql/cleanup-add-batch-updates.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12208 [batch] Add index on jobs for update id
  batch/sql/add-jobs-update-id-index.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: prio:high, migration

#12199 [batch] Open Batches!
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/templates/batch.html
  batch/batch/front_end/templates/batches.html
  batch/batch/front_end/validate.py
  batch/batch/globals.py
  batch/sql/add-commit-updates.sql
  batch/sql/delete-batch-tables.sql
  batch/sql/estimated-current.sql
  batch/test/test_accounts.py
  batch/test/test_batch.py
  build.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
Labels: migration

#12234 [batch] Return the start_job_id from _create_job_update when the update exists
  batch/batch/front_end/front_end.py
Labels: prio:high

#12238 [batch] Fix update_batch_no_deps test to wait for all jobs
  batch/test/test_batch.py
Labels: prio:high
