Repository hail-is/hail, pull requests merged in 2023-03, with the labels that each got.

#12745 [batch/ci] Address ServiceAccount token changes in Kubernetes 1.24
  batch/batch/driver/job.py
  batch/test-sa.yaml
  ci/bootstrap.py
  ci/bootstrap.yaml
  ci/ci-agent.yaml
  ci/ci/build.py
Labels: prio:high

#12749 [batch] downgrade gcsfuse to avoid gcsfuse bug
  batch/Dockerfile.worker
Labels: prio:high

#12724 [batch] Create resource id dedup map
  batch/sql/create_resource_dedup_mapping.py
  build.yaml
Labels: prio:high, migration

#12755 [db] Add namespace to migrations environment
  ci/create_database.py
Labels: full-deploy

#12756 [ci] Fix default namespace record for dev namespaces
  build.yaml
  ci/sql/fix-default-namespace.py
Labels: migration

#12771 [query] update jgscm in init_notebook
  hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Labels: prio:high

#12770 [release] 0.2.110
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
Labels: prio:high

#12742 [batch] Allow more than one standing worker
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/main.py
  batch/batch/driver/templates/pool.html
  batch/batch/inst_coll_config.py
  batch/sql/config-pool-min-instances.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12781 [query][scripts][website][ukbb-rg] gsutil => gcloud
  hail/Makefile
  hail/python/hail/docs/cloud/azure.rst
  hail/python/hailtop/batch/docs/docker_resources.rst
  hail/python/hailtop/batch/docs/service.rst
  hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
  hail/scripts/deploy.sh
  hail/scripts/test-gcp.sh
  ukbb-rg/Makefile
  website/Makefile
Labels: prio:high

#12784 [query] Dont use memory service
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/backend/service/Worker.scala
Labels: prio:high

#12785 [release] 0.2.112
  hail/python/hail/docs/change_log.md
Labels: prio:high

#12787 [release] 0.2.112 for real this time
  hail/Makefile
Labels: prio:high

#12791 [docker] Update gcloud to a version that has the storage subcommand
  docker/Dockerfile.base
Labels: prio:high

#12811 [ci] Always build the dev image
  build.yaml
Labels: prio:high

#12815 [batch] Don't check invariants every 10 seconds in test PRs
  batch/batch/batch_configuration.py
  batch/batch/driver/main.py
  batch/deployment.yaml
  batch/test/test_invariants.py
Labels: prio:high
