Repository hail-is/hail, pull requests merged in 2023-05, with the labels that each got.

#12959 [batch] xfail highcpu cheapest test
  batch/test/test_batch.py
Labels: prio:high

#12972 [batch] Restore read-only cloudfuse
  batch/batch/front_end/front_end.py
  batch/batch/worker/worker.py
  hail/python/test/hailtop/batch/test_batch.py
Labels: prio:high

#12987 updates changelog for 0.2.116
  build.yaml
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/scripts/deploy.sh
Labels: prio:high

#13020 [batch] without auto-create subnetworks, you must specify a subnet
  batch/batch/cloud/gcp/driver/create_instance.py
Labels: prio:high

#13004 [ci] Run service backend tests on non-preemptibles
  build.yaml
Labels: prio:high

#13021 [services] retry five times instead of once
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#13023 [services] restore logging
  hail/python/hailtop/hail_logging.py
Labels: prio:high

#13032 [services] update azure-storage-blob 12.22.0 to mitigate "Stream is already closed"
  hail/build.gradle
  hail/scripts/upload_qob_jar.sh
  hail/settings.gradle
  hail/shadedazure/build.gradle
  hail/src/main/resources/META-INF.services/com.azure.core.http.HttpClientProvider
  hail/src/main/resources/META-INF.services/is.hail.shadedazure.com.azure.core.http.HttpClientProvider
  hail/src/main/resources/META-INF/services/com.azure.core.http.HttpClientProvider
  hail/src/main/resources/META-INF/services/com.ctc.wstx.shaded.msv.relaxng_datatype.DatatypeLibraryFactory
  hail/src/main/resources/META-INF/services/com.ctc.wstx.stax.WstxInputFactory
  hail/src/main/resources/META-INF/services/com.fasterxml.jackson.core.JsonFactory
  hail/src/main/resources/META-INF/services/com.fasterxml.jackson.core.ObjectCodec
  hail/src/main/resources/META-INF/services/com.fasterxml.jackson.databind.Module
  hail/src/main/resources/META-INF/services/io.micrometer.context.ContextAccessor
  hail/src/main/resources/META-INF/services/is.hail.shadedazure.com.azure.core.http.HttpClientProvider
  hail/src/main/resources/META-INF/services/javax.xml.stream.XMLEventFactory
  hail/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory
  hail/src/main/resources/META-INF/services/javax.xml.stream.XMLOutputFactory
  hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory
  hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.dtd
  hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.relaxng
  hail/src/main/resources/META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c
  hail/src/main/resources/META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
  hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#13036 [batch] Allow private job network traffic to internal IPs
  batch/batch/cloud/gcp/driver/create_instance.py
Labels: prio:high

#13031 [query] Better message for LocalLDPrune only taking diploid calls
  hail/src/main/scala/is/hail/methods/LocalLDPrune.scala
Labels: tiny PR

#13030 [ci] Create a test MySQL server in test and dev namespaces
  build.yaml
  ci/ci/build.py
  ci/create_database.py
  ci/create_initial_account.py
  ci/test/resources/build.yaml
  docker/mysql/db.yaml
  gear/gear/__init__.py
  gear/gear/database.py
  hail/python/hailtop/auth/sql_config.py
  tls/Dockerfile
  tls/create_test_db_config.sh
Labels: prio:high

#13060 [hailctl] fix init_notebook.py requirements to be compatible with Hail
  hail/python/hailtop/hailctl/dataproc/resources/init_notebook.py
Labels: prio:high

#12817 [batch] Populate aggregated billing project users table
  batch/sql/dedup_billing_project_users.py
  build.yaml
Labels: prio:high, migration

#13069 [batch] Fix dedup billing project user resources audit
  batch/sql/dedup_billing_project_users.py
Labels: prio:high, migration

#13043 [transient-errors] will it ever end?
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#13065 [qob] remove resource leak in readNoCompression
  batch/batch/driver/instance_collection/base.py
  hail/python/dev/pinned-requirements.txt
  hail/python/dev/requirements.txt
  hail/python/hailtop/fs/router_fs.py
  hail/python/hailtop/httpx.py
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
  hail/src/main/scala/is/hail/io/fs/FS.scala
Labels: prio:high

#13090 [test-dataproc] add subnet
  hail/scripts/test-dataproc.sh
Labels: prio:high

#13083 [batch] Fix attempt resources after update trigger to use deduped resource id
  batch/sql/estimated-current.sql
  batch/sql/fix-billing-triggers-deduped-resource-id.sql
  build.yaml
Labels: migration
