Repository hail-is/hail, pull requests merged in 2023-06, with the labels that each got.

#13145 [query] a few more timeout relaxations or test splits
  batch/test/test_batch.py
  hail/python/test/hail/methods/test_family_methods.py
Labels: prio:high

#13147 [query] split tests, faster test dataset, longer timeout for big test
  batch/test/test_accounts.py
  batch/test/test_batch.py
  build.yaml
  hail/python/hail/backend/service_backend.py
  hail/python/test/hail/backend/test_service_backend.py
  hail/python/test/hail/helpers.py
  hail/python/test/hail/linalg/test_linalg.py
  hail/python/test/hail/matrixtable/test_matrix_table.py
  hail/python/test/hail/methods/relatedness/test_pc_relate.py
  hail/python/test/hail/methods/test_skat.py
  hail/src/test/resources/split-multi-sample.vcf.mt/README.txt
  hail/src/test/resources/split-multi-sample.vcf.mt/_SUCCESS
  hail/src/test/resources/split-multi-sample.vcf.mt/cols/README.txt
  hail/src/test/resources/split-multi-sample.vcf.mt/cols/_SUCCESS
  hail/src/test/resources/split-multi-sample.vcf.mt/cols/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/cols/rows/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/cols/rows/parts/part-0
  hail/src/test/resources/split-multi-sample.vcf.mt/entries/README.txt
  hail/src/test/resources/split-multi-sample.vcf.mt/entries/_SUCCESS
  hail/src/test/resources/split-multi-sample.vcf.mt/entries/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/entries/rows/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/entries/rows/parts/part-0-3b5ee9e6-b5ea-4a0f-8834-d0508563c64d
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/README.txt
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/_SUCCESS
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/globals/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/globals/parts/part-0
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/rows/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/globals/rows/parts/part-0
  hail/src/test/resources/split-multi-sample.vcf.mt/index/part-0-3b5ee9e6-b5ea-4a0f-8834-d0508563c64d.idx/index
  hail/src/test/resources/split-multi-sample.vcf.mt/index/part-0-3b5ee9e6-b5ea-4a0f-8834-d0508563c64d.idx/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/rows/README.txt
  hail/src/test/resources/split-multi-sample.vcf.mt/rows/_SUCCESS
  hail/src/test/resources/split-multi-sample.vcf.mt/rows/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/rows/rows/metadata.json.gz
  hail/src/test/resources/split-multi-sample.vcf.mt/rows/rows/parts/part-0-3b5ee9e6-b5ea-4a0f-8834-d0508563c64d
Labels: prio:high

#13153 [query] spectra_and_moments_1 also takes a long time in spark??
  build.yaml
  hail/python/test/hail/methods/test_impex.py
  hail/python/test/hail/methods/test_pca.py
Labels: prio:high

#13155 [ci][batch] mitigate some instability
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  build.yaml
  ci/ci/github.py
  ci/test/resources/build.yaml
  ci/test/resources/deployment.yaml
  ci/test/resources/statefulset.yaml
  hail/python/test/hailtop/batch/test_batch.py
  hail/python/test/hailtop/batch/test_batch_pool_executor.py
Labels: prio:high

#13164 [auth] mirror the batch settings for non-deploy
  auth/deployment.yaml
Labels: prio:high

#13127 [release] updates changelog for 0.2.118
  hail/Makefile
  hail/python/hail/docs/change_log.md
Labels: prio:high

#13171 [query] skip comments when parsing spark-defaults.conf
  auth/pinned-requirements.txt
  batch/pinned-requirements.txt
  ci/pinned-requirements.txt
  gear/pinned-requirements.txt
  hail/python/dev/pinned-requirements.txt
  hail/python/hailtop/aiocloud/aiogoogle/user_config.py
  hail/python/hailtop/pinned-requirements.txt
  hail/python/hailtop/requirements.txt
  hail/python/pinned-requirements.txt
  hail/python/test/hailtop/hailctl/dataproc/conftest.py
  web_common/pinned-requirements.txt
Labels: prio:high

#13117 [batch] Fix audit for the deduping bp user resources migration
  batch/sql/dedup_billing_project_users_v2.py
  build.yaml
Labels: migration

#12748 [batch] Add new list_jobs query interface to REST calls
  batch/batch/exceptions.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/query/__init__.py
  batch/batch/front_end/query/operators.py
  batch/batch/front_end/query/query.py
  batch/batch/front_end/query/query_v1.py
  batch/batch/front_end/query/query_v2.py
  batch/sql/estimated-current.sql
  batch/sql/list-jobs-extra-indices.sql
  batch/test/test_batch.py
  build.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
Labels: migration

#13203 [batch] Mount worker deploy config instead of using k8s secret
  batch/batch/cloud/azure/driver/create_instance.py
  batch/batch/cloud/gcp/driver/create_instance.py
  batch/batch/front_end/front_end.py
  batch/batch/globals.py
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  hail/python/hailtop/config/deploy_config.py
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/backend/service/Worker.scala
Labels: full-deploy

#13211 No worker deploy config secret
  batch/batch/cloud/azure/driver/create_instance.py
  batch/batch/cloud/gcp/driver/create_instance.py
  batch/batch/front_end/front_end.py
  batch/batch/globals.py
  batch/batch/worker/worker.py
  batch/test/test_batch.py
  hail/python/hailtop/config/deploy_config.py
Labels: full-deploy

#12847 [batch] Populate billing project users by date deduped table
  batch/sql/dedup_billing_project_users_by_date.py
  build.yaml
Labels: prio:high, migration

#13207 [auth] Add internal hail identity UIDs to the users table
  auth/auth/driver/driver.py
  auth/sql/add-hail-identity-uid.sql
  auth/sql/estimated-current.sql
  build.yaml
  gear/gear/clients.py
  hail/python/hailtop/aiocloud/aioazure/client/graph_client.py
Labels: full-deploy

#13219 [batch] Add identifying metadata to Batch requests
  batch/batch/driver/instance_collection/job_private.py
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/batch/front_end/front_end.py
  batch/batch/utils.py
  batch/batch/worker/worker.py
  batch/sql/add-jobs-ready-time.sql
  batch/sql/estimated-current.sql
  build.yaml
  hail/python/hailtop/hail_logging.py
Labels: migration
