Repository hail-is/hail, pull requests merged in 2023-04, with the labels that each got.

#12854 [qob] Read results files 20x faster by not using Scala parallel collections
  hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala
  hail/src/main/scala/is/hail/io/fs/FS.scala
  hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
  hail/src/main/scala/is/hail/io/fs/RouterFS.scala
Labels: prio:high

#12855 [qob] allow writing to requester pays buckets
  hail/python/hail/backend/backend.py
  hail/python/hail/backend/local_backend.py
  hail/python/hail/backend/service_backend.py
  hail/python/hail/backend/spark_backend.py
  hail/python/hail/experimental/function.py
  hail/python/hail/experimental/vcf_combiner/vcf_combiner.py
  hail/python/hail/vds/combiner/combine.py
  hail/python/test/hail/fs/test_worker_driver_fs.py
  hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
Labels: prio:high

#12869 [qob] Fix new transiencies
  hail/python/hail/backend/service_backend.py
  hail/src/main/scala/is/hail/io/fs/GoogleStorageFS.scala
Labels: prio:high

#12874 [ci] Put ci-utils on top of base image
  Makefile
  build.yaml
  ci/Dockerfile.ci-utils
  ci/test/resources/build.yaml
Labels: prio:high

#12860 [query] Fix memory leak in buffered aggregation / shuffles on QoB
  hail/src/main/scala/is/hail/expr/ir/streams/EmitStream.scala
Labels: prio:high

#12786 [batch] Add deduped resource id column to attempt resources table
  batch/batch/driver/job.py
  batch/sql/add-deduped-resource-ids-to-attempt-resources.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#12899 [hailctl] Improve startup time by removing big top-level imports
  hail/python/hailtop/utils/utils.py
Labels: tiny PR

#12937 [build.yaml][ci] upgrade to skopeo 1.12.0
  build.yaml
  ci/Dockerfile.ci-utils
Labels: prio:high

#12938 [query] revert to skopeo 1.11.2
  build.yaml
  ci/Dockerfile.ci-utils
Labels: prio:high

#12944 [batch] Add timeouts to ensure that post_job_complete is reached
  batch/batch/worker/worker.py
  build.yaml
Labels: prio:high

#12942 [batch] Fix bad insert attempt resources trigger
  batch/sql/estimated-current.sql
  batch/sql/mitigate-bad-attempt-resources-trigger.sql
  build.yaml
Labels: prio:high, migration

#12949 [batch] Turn off support for cloudfuse
  batch/batch/front_end/front_end.py
Labels: prio:high
