Repository hail-is/hail, pull requests merged in 2023-09, with the labels that each got.

#13562 [batch] Use the test and test-dev GSAs in test_batch not CI
  batch/batch/globals.py
  batch/test/billing_projects.py
  batch/test/test_accounts.py
  build.yaml
  hail/python/hailtop/auth/auth.py
  hail/python/hailtop/batch_client/aioclient.py
Labels: prio:high

#13529 [release] 0.2.121
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
Labels: prio:high

#13573 [test-dataproc] make test-dataproc-37 and -38 not race
  build.yaml
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh37.sh
  hail/python/hailtop/hailctl/dataproc/resources/vep-GRCh38.sh
Labels: prio:high

#13585 [hailtop] Fix defaulting to hail.is when the user has no deploy-config
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
  hail/python/hailtop/config/deploy_config.py
Labels: prio:high

#13628 [ci] Fix errant line in environment variable spec
  ci/deployment.yaml
Labels: prio:high

#13610 [query/ggplot] runs plotting notebook setup on import
  build.yaml
  hail/python/hail/docs/tutorials/08-plotting.ipynb
  hail/python/hail/docs/tutorials/09-ggplot.ipynb
  hail/python/hail/ggplot/__init__.py
  hail/python/hail/plot/__init__.py
  hail/python/hailtop/__init__.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/utils/rich_progress_bar.py
Labels: prio:high

#13612 [ci] Support docker build args in buildImage steps
  Makefile
  admin-pod/Dockerfile
  auth/Dockerfile
  batch/Dockerfile
  batch/Dockerfile.worker
  blog/Dockerfile.nginx
  bootstrap-gateway/Dockerfile
  build.yaml
  ci/Dockerfile
  ci/Dockerfile.ci-utils
  ci/buildkit/Dockerfile
  ci/ci/build.py
  ci/test/resources/Dockerfile
  ci/test/resources/build.yaml
  docker-build.sh
  docker/Dockerfile.base
  docker/Dockerfile.hail-dev
  docker/hail-ubuntu/Dockerfile
  docker/hailgenetics/vep/grch37/85/Dockerfile
  docker/hailgenetics/vep/grch38/95/Dockerfile
  hail/Dockerfile.hail-run
  infra/gcp-broad/gcp-ar-cleanup-policy.txt
  monitoring/Dockerfile
  query/Dockerfile.query-build
  tls/Dockerfile
  ukbb-rg/Dockerfile.browser
  ukbb-rg/Dockerfile.static
  website/Dockerfile
Labels: full-deploy

#13648 [query/ggplot] makes plotting setup lazy
  .gitignore
  hail/python/hail/ggplot/__init__.py
  hail/python/hail/plot/__init__.py
  hail/python/hailtop/__init__.py
  hail/python/hailtop/batch_client/aioclient.py
Labels: prio:high

#13649 [vds] fix documentation typo
  hail/python/hail/vds/methods.py
Labels: tiny PR

#13658 [query] Give test_ld_prune more time on the batch backend
  hail/python/test/hail/methods/test_statgen.py
Labels: prio:high

#13659 [release] 0.2.123
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/backend.py
  hail/python/hailtop/batch/batch_pool_executor.py
  hail/python/hailtop/batch/docs/change_log.rst
Labels: prio:high

#13662 [deploy] Fix deploy.sh script
  hail/scripts/deploy.sh
Labels: prio:high

#13652 [gear] Dont cache the db ssl context in a global
  gear/gear/database.py
Labels: tiny PR

#13681 [hailctl] Fixes for first time init
  hail/Makefile
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/aiotools/copy.py
  hail/python/hailtop/batch/docs/change_log.rst
  hail/python/hailtop/config/__init__.py
  hail/python/hailtop/hailctl/auth/login.py
  hail/python/hailtop/hailctl/batch/initialize.py
Labels: prio:high

#13683 [deploy] Update PyPI assertion to not use more than 20GiB at PyPI
  hail/scripts/assert_pypi_has_room.py
Labels: prio:high

#13607 [batch] Add SKU to latest_product_versions
  batch/batch/cloud/azure/driver/billing_manager.py
  batch/batch/cloud/azure/driver/pricing.py
  batch/batch/cloud/gcp/driver/billing_manager.py
  batch/batch/cloud/gcp/driver/pricing.py
  batch/batch/driver/billing_manager.py
  batch/batch/driver/pricing.py
  batch/batch/inst_coll_config.py
  batch/sql/add-product-sku.sql
  batch/sql/estimated-current.sql
  build.yaml
Labels: migration

#13741 [batch] Ignore client_job attribute in test_callback test
  batch/test/test_dag.py
Labels: prio:high
