Repository hail-is/hail, pull requests merged in 2023-08, with the labels that each got.

#13344 [azure] Add connection timeouts for Azure FS in both Python and Scala
  hail/python/hailtop/aiocloud/aioazure/fs.py
  hail/src/main/scala/is/hail/io/fs/AzureStorageFS.scala
Labels: prio:high

#13354 [services] use AWS-inspired retry delays
  batch/batch/resource_usage.py
  batch/batch/worker/worker_api.py
  batch/test/test_batch.py
  gear/gear/database.py
  hail/python/hailtop/aiocloud/aioazure/client/base_client.py
  hail/python/hailtop/aiocloud/aiogoogle/client/compute_client.py
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/hailctl/auth/create_user.py
  hail/python/hailtop/hailctl/auth/delete_user.py
  hail/python/hailtop/hailctl/hdinsight/submit.py
  hail/python/hailtop/utils/__init__.py
  hail/python/hailtop/utils/utils.py
  hail/python/test/hailtop/batch/test_batch_pool_executor.py
  hail/src/main/scala/is/hail/services/package.scala
Labels: prio:high

#13341 [query/vds] fix transform_gvcf docs
  hail/python/hail/vds/combiner/combine.py
Labels: tiny PR

#13373 [batch] Fix transaction decorator to work with additional args
  batch/batch/driver/main.py
  gear/gear/database.py
Labels: prio:high

#13415 [build.yaml] use an acocunt that actually has admin privs
  build.yaml
Labels: prio:high

#13412 [batch] Up network allocation timeout to a minute
  batch/batch/worker/worker.py
Labels: prio:high

#13420 [ci] Use ci-agent not ci-admin for cron
  build.yaml
Labels: prio:high

#13414 [compiler] fix TableUnion lowering
  hail/python/test/hail/table/test_table.py
  hail/src/main/scala/is/hail/expr/ir/lowering/LowerTableIR.scala
Labels: prio:high

#13443 [prometheus] update to 2.46.0 to attempt to avoid WAL issues
  prometheus/prometheus.yaml
Labels: prio:high

#13473 [ci] fix borked CI
  ci/ci/build.py
  ci/ci/github.py
Labels: prio:high

#13463 [batch/ui] adds advanced search box and help link
  batch/batch/front_end/query/__init__.py
  batch/batch/front_end/templates/batch.html
  batch/batch/front_end/templates/batches.html
  batch/batch/front_end/templates/table_search.html
Labels: prio:high

#13493 [batch] Fix default query to match v2
  batch/batch/front_end/front_end.py
Labels: prio:high

#13510 [batch] Drop unused SQL functions
  batch/sql/cleanup-deprecated-functions.sql
  batch/sql/estimated-current.sql
Labels: prio:low, migration

#13514 [batch] Actually do the cleanup unused functions migration
  build.yaml
Labels: migration

#13521 [batch] Dont treat unknown in DockerError 500s as transient
  build.yaml
  hail/python/hailtop/utils/utils.py
Labels: prio:high

#13527 [ci] Use skopeo 1.13.2
  build.yaml
Labels: prio:high

#13519 [batch] Name the batch worker container
  batch/batch/cloud/azure/driver/create_instance.py
  batch/batch/cloud/gcp/driver/create_instance.py
Labels: tiny PR
