Repository hail-is/hail, pull requests merged in 2024-02, with the labels that each got.

#14190 [batch] Update IP Fee pricing for February 2024 price increase
  batch/batch/cloud/gcp/instance_config.py
  batch/batch/cloud/gcp/resources.py
  batch/sql/update-ip-fee-resource.py
  build.yaml
  hail/python/hailtop/batch/docs/service.rst
Labels: migration

#14283 [algolia] update to current "application"
  website/website/pages/search.html
Labels: prio:high

#13893 [batch] Remove all v2 billing tables
  batch/sql/estimated-current.sql
  batch/sql/remove-v2-billing-tables.sql
  build.yaml
Labels: migration

#14304 [release] Release 0.2.128
  hail/build.sc
  hail/python/hail/docs/change_log.md
  hail/version.mk
Labels: prio:high

#14301 [ci] Use CI's credentials for image pushing instead of gcr-push
  build.yaml
  ci/ci/build.py
  infra/gcp-broad/main.tf
  infra/gcp/main.tf
Labels: full-deploy

#14307 [ci] Remove unused arguments to release script
  build.yaml
  hail/python/hail/docs/change_log.md
Labels: prio:high

#14310 [batch] fix handle_arg and fix unused TypeVar
  gear/pinned-requirements.txt
  gear/requirements.txt
  hail/python/hailtop/batch/job.py
  hail/python/hailtop/pinned-requirements.txt
  hail/python/hailtop/requirements.txt
  hail/python/hailtop/utils/utils.py
  hail/python/pinned-requirements.txt
Labels: prio:high

#14282 [batch] Add Job Groups to Batch
  batch/batch/batch.py
  batch/batch/constants.py
  batch/batch/driver/canceller.py
  batch/batch/driver/instance_collection/job_private.py
  batch/batch/driver/instance_collection/pool.py
  batch/batch/driver/job.py
  batch/batch/driver/main.py
  batch/batch/exceptions.py
  batch/batch/front_end/front_end.py
  batch/batch/front_end/query/__init__.py
  batch/batch/front_end/query/query.py
  batch/batch/front_end/query/query_v1.py
  batch/batch/front_end/query/query_v2.py
  batch/batch/front_end/validate.py
  batch/batch/globals.py
  batch/batch/utils.py
  batch/batch/worker/worker.py
  batch/sql/estimated-current.sql
  batch/sql/finalize-job-groups.sql
  batch/test/test_accounts.py
  batch/test/test_batch.py
  batch/test/test_dag.py
  build.yaml
  hail/python/hailtop/batch_client/aioclient.py
  hail/python/hailtop/batch_client/client.py
  hail/python/hailtop/batch_client/globals.py
  hail/python/hailtop/batch_client/types.py
Labels: prio:high, migration

#14366 [batch] reduce CPU use of delete_prev_..._resource_records
  batch/batch/driver/main.py
Labels: prio:high

#14373 [batch] Correct ordering of batch_id and job_group_id in mark_job_errored
  batch/batch/driver/job.py
Labels: prio:high

#14374 [internal-gateway] Greatly reduce rate limit for batch-driver requests from workers
  ci/ci/envoy.py
Labels: prio:high

#14377 [batch] reduce runtime of listing batches and job groups
  batch/batch/front_end/query/query_v1.py
  batch/batch/front_end/query/query_v2.py
Labels: prio:high

#14379 [batch] Dont grab an X lock on the batches table in attempts after update
  batch/sql/estimated-current.sql
  batch/sql/fix-mark-job-complete-deadlocks.sql
  build.yaml
Labels: prio:high, migration

#14387 Revert "[internal-gateway] Greatly reduce rate limit for batch-driver requests from workers"
  ci/ci/envoy.py
Labels: prio:high
