Repository hail-is/hail, pull requests merged in 2024-04, with the labels that each got.

#14434 [release] Retry 0.2.129
  build.yaml
  hail/Makefile
  hail/scripts/release.sh
Labels: prio:high

#14436 [release] Fix EV syntax in release job for WHEEL variable
  build.yaml
Labels: prio:high

#14438 [release] split export statements out of desperation more than anything
  build.yaml
Labels: prio:high

#14445 [release] dont rely on release.sh being executable
  build.yaml
  hail/Makefile
  hail/scripts/release.sh
Labels: prio:high, do-not-test

#14437 [batch] Use spend instead of cost on the billing page
  batch/batch/front_end/templates/billing.html
Labels: snack

#14453 [release] build release wheel with correct `deploy.yaml`
  build.yaml
Labels: prio:high

#14454 [release] 0.2.130
  hail/build.sc
  hail/python/hail/docs/change_log.md
  hail/python/hailtop/batch/docs/change_log.rst
  hail/version.mk
Labels: prio:high

#14476 Revert "[ci] Poll for batch and github changes every 1 minute instead of 5"
  ci/ci/ci.py
Labels: prio:high
